//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

// #import "UIView.h"

// #import "HPADDelegate.h"
// #import "HPGPostListTVCDelegate.h"
// #import "UIAlertViewDelegate.h"
// #import "UITableViewDataSource.h"
// #import "UITableViewDelegate.h"

@class ASIHTTPRequest, BBSBoardListHeadView, BBSCategoryListItem, HPTipsView, NSArray, NSMutableArray, NSMutableDictionary, NSString, UIActivityIndicatorView, UIButton, UIRefreshControl, UIScrollView, UITableView;

@interface BBSBoardListTableView : UIView <UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate>
// {
//     NSMutableArray *adDataArray;
//     _Bool _hasEssence;
//     _Bool _hasNextPage_reply;
//     _Bool _hasNextPage_post;
//     _Bool _hasNextPage_essence;
//     _Bool _isRequest;
//     int _currentRequestIndex;
//     int _newreplyRequestPage;
//     int _newpostRequestPage;
//     int _essenceRequestPage;
//     CDUnknownBlockType _alphaBlock;
//     NSArray *_tabsArray;
//     BBSCategoryListItem *_item;
//     NSString *_fid;
//     NSString *_password;
//     NSString *_categoryName;
//     UIScrollView *_scrollView;
//     BBSBoardListHeadView *_tableHeadView;
//     UIView *_tableHeadTool;
//     UIView *_toolLine;
//     UITableView *_newreplyTableView;
//     UITableView *_newpostTableView;
//     UITableView *_essenceTableView;
//     UIRefreshControl *_newreplyrefreshControl;
//     UIRefreshControl *_newpostrefreshControl;
//     UIRefreshControl *_essencerefreshControl;
//     NSMutableArray *_newreplydataArray;
//     NSMutableArray *_newpostdataArray;
//     NSMutableArray *_essencedataArray;
//     NSMutableDictionary *_newereplydiffDictionary;
//     NSMutableDictionary *_newpostdiffDictionary;
//     NSMutableDictionary *_essencediffDictionary;
//     UIActivityIndicatorView *_activityView;
//     ASIHTTPRequest *_dataRequest;
//     long long _newreplyStamp;
//     long long _newpostStamp;
//     long long _essenceStamp;
//     ASIHTTPRequest *_followRequest;
//     HPTipsView *_followTipsView;
//     UIButton *_btnFollow;
// }

- (void)HPADClickAd:(id)arg1 url:(id)arg2;
- (void)HPADDidFailToReceiveAd:(id)arg1 didFailWithError:(id)arg2;
- (void)HPADDidReceiveAd:(id)arg1;
- (void)HPADViewClosed:(id)arg1;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
- (void)addADInfoForCell:(id)arg1 indexPath:(id)arg2 item:(id)arg3;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
// @property(copy, nonatomic) CDUnknownBlockType alphaBlock; // @synthesize alphaBlock=_alphaBlock;
@property(retain, nonatomic) UIButton *btnFollow; // @synthesize btnFollow=_btnFollow;
@property(copy, nonatomic) NSString *categoryName; // @synthesize categoryName=_categoryName;
@property(nonatomic) int currentRequestIndex; // @synthesize currentRequestIndex=_currentRequestIndex;
@property(readonly, nonatomic) NSMutableArray *dataArray;
@property(retain, nonatomic) ASIHTTPRequest *dataRequest; // @synthesize dataRequest=_dataRequest;
- (void)dealloc;
- (void)didSelectDeleteBtAction:(id)arg1 cell:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *diffDictionary;
@property(nonatomic) int essenceRequestPage; // @synthesize essenceRequestPage=_essenceRequestPage;
@property(nonatomic) long long essenceStamp; // @synthesize essenceStamp=_essenceStamp;
@property(retain, nonatomic) UITableView *essenceTableView; // @synthesize essenceTableView=_essenceTableView;
@property(retain, nonatomic) NSMutableArray *essencedataArray; // @synthesize essencedataArray=_essencedataArray;
@property(retain, nonatomic) NSMutableDictionary *essencediffDictionary; // @synthesize essencediffDictionary=_essencediffDictionary;
@property(retain, nonatomic) UIRefreshControl *essencerefreshControl; // @synthesize essencerefreshControl=_essencerefreshControl;
@property(retain, nonatomic) NSString *fid; // @synthesize fid=_fid;
- (void)follow:(_Bool)arg1;
- (void)followAction:(_Bool)arg1;
@property(retain, nonatomic) ASIHTTPRequest *followRequest; // @synthesize followRequest=_followRequest;
@property(retain, nonatomic) HPTipsView *followTipsView; // @synthesize followTipsView=_followTipsView;
- (id)getCacheDocument;
- (void)goToAds;
@property(nonatomic) _Bool hasEssence; // @synthesize hasEssence=_hasEssence;
@property(nonatomic) _Bool hasNextPage;
@property(nonatomic) _Bool hasNextPage_essence; // @synthesize hasNextPage_essence=_hasNextPage_essence;
@property(nonatomic) _Bool hasNextPage_post; // @synthesize hasNextPage_post=_hasNextPage_post;
@property(nonatomic) _Bool hasNextPage_reply; // @synthesize hasNextPage_reply=_hasNextPage_reply;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (long long)indexForADView:(id)arg1;
- (void)initData;
- (id)initHasEssence:(_Bool)arg1 tabsArray:(id)arg2;
- (void)initHeadTool;
- (void)initHeadView;
- (void)initScrollView;
- (void)initView;
@property(nonatomic) _Bool isRequest; // @synthesize isRequest=_isRequest;
@property(retain, nonatomic) BBSCategoryListItem *item; // @synthesize item=_item;
@property(retain, nonatomic) NSMutableDictionary *newereplydiffDictionary; // @synthesize newereplydiffDictionary=_newereplydiffDictionary;
@property(nonatomic) int newpostRequestPage; // @synthesize newpostRequestPage=_newpostRequestPage;
@property(nonatomic) long long newpostStamp; // @synthesize newpostStamp=_newpostStamp;
@property(retain, nonatomic) UITableView *newpostTableView; // @synthesize newpostTableView=_newpostTableView;
@property(retain, nonatomic) NSMutableArray *newpostdataArray; // @synthesize newpostdataArray=_newpostdataArray;
@property(retain, nonatomic) NSMutableDictionary *newpostdiffDictionary; // @synthesize newpostdiffDictionary=_newpostdiffDictionary;
@property(retain, nonatomic) UIRefreshControl *newpostrefreshControl; // @synthesize newpostrefreshControl=_newpostrefreshControl;
@property(nonatomic) int newreplyRequestPage; // @synthesize newreplyRequestPage=_newreplyRequestPage;
@property(nonatomic) long long newreplyStamp; // @synthesize newreplyStamp=_newreplyStamp;
@property(retain, nonatomic) UITableView *newreplyTableView; // @synthesize newreplyTableView=_newreplyTableView;
@property(retain, nonatomic) NSMutableArray *newreplydataArray; // @synthesize newreplydataArray=_newreplydataArray;
@property(retain, nonatomic) UIRefreshControl *newreplyrefreshControl; // @synthesize newreplyrefreshControl=_newreplyrefreshControl;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
- (void)preparForLoadADData:(long long)arg1;
- (void)prepareForAdData;
@property(retain, nonatomic) UIRefreshControl *refreshControl;
- (void)refreshTable:(id)arg1;
- (void)reloadViewColor;
- (void)request;
@property(nonatomic) int requestPage;
- (void)requsetFinished;
- (void)scrollToTop;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)sepBtAction:(id)arg1;
- (void)setNavBarAlpha:(double)arg1 height:(double)arg2;
@property(nonatomic) long long stamp;
@property(retain, nonatomic) UIView *tableHeadTool; // @synthesize tableHeadTool=_tableHeadTool;
@property(retain, nonatomic) BBSBoardListHeadView *tableHeadView; // @synthesize tableHeadView=_tableHeadView;
@property(retain, nonatomic) NSArray *tabsArray; // @synthesize tabsArray=_tabsArray;
@property(retain, nonatomic) UIView *toolLine; // @synthesize toolLine=_toolLine;
- (void)showADWithADData:(id)arg1;
@property(readonly, nonatomic) UITableView *tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tapFollowBtn:(id)arg1;
- (void)updateFollowBtn;
- (void)updateRedLinePoint:(double)arg1;
- (void)updatemForumsArray:(id)arg1;

@end

