//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ASIHTTPRequest, HPFullScreenADView, HPScrollRefreshView_LittleYellowLight, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, SPAutoCodingWarp, UIActivityIndicatorView, UIButton;

@interface HPGRecommendPostListTVC : UITableViewController

- (void)HPADClickAd:(id)arg1 url:(id)arg2;
- (void)HPADDidFailToReceiveAd:(id)arg1 didFailWithError:(id)arg2;
- (void)HPADDidReceiveAd:(id)arg1;
- (void)HPADViewClosed:(id)arg1;
- (void)addADInfoForCell:(id)arg1 indexPath:(id)arg2 item:(id)arg3;
@property(retain, nonatomic) NSString *additionTid; // @synthesize additionTid=_additionTid;
@property(retain, nonatomic) UIButton *adsButton; // @synthesize adsButton=_adsButton;
@property(nonatomic) int adsCount; // @synthesize adsCount=_adsCount;
@property(retain, nonatomic) NSString *adsUrlStr; // @synthesize adsUrlStr=_adsUrlStr;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)animationAds;
@property(retain, nonatomic) NSDictionary *attentionDic; // @synthesize attentionDic=_attentionDic;
@property(retain, nonatomic) SPAutoCodingWarp *boradModel; // @synthesize boradModel=_boradModel;
- (void)changeNetWork;
- (void)clearRequest;
- (void)closeAds;
- (void)dealloc;
- (void)delayRefreshHead:(_Bool)arg1;
- (void)deleteAD:(id)arg1 withforumDict:(id)arg2;
- (void)deleteRecommend:(id)arg1 withforumDict:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)didSelectAttendBtAction:(id)arg1 cell:(id)arg2;
- (void)didSelectDeleteBtAction:(id)arg1 cell:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *diffDictionary; // @synthesize diffDictionary=_diffDictionary;
- (void)enterBackgroud;
- (void)enterForge;
@property(retain, nonatomic) ASIHTTPRequest *forumReq; // @synthesize forumReq=_forumReq;
- (void)forumTappedWithForumDict:(id)arg1;
- (void)fullScreenADViewShowAnimation;
@property(retain, nonatomic) HPFullScreenADView *fullScreenAdView; // @synthesize fullScreenAdView=_fullScreenAdView;
- (id)getCacheDocument;
- (id)getFollowEnNames;
- (id)getFollowTeams;
- (void)goToAds;
- (void)gotoLogin;
- (long long)indexForADView:(id)arg1;
- (id)initFresh;
- (void)initNoDataView;
@property(nonatomic) _Bool isFreshList; // @synthesize isFreshList=_isFreshList;
@property(nonatomic) _Bool isFromeRefreshRecommendBBS; // @synthesize isFromeRefreshRecommendBBS=_isFromeRefreshRecommendBBS;
@property(nonatomic) _Bool isLoadIngNext; // @synthesize isLoadIngNext=_isLoadIngNext;
@property(nonatomic) _Bool isRequest; // @synthesize isRequest=_isRequest;
@property(nonatomic) _Bool isShowAdsHead; // @synthesize isShowAdsHead=_isShowAdsHead;
@property(nonatomic) _Bool isShowAlert; // @synthesize isShowAlert=_isShowAlert;
@property(nonatomic) long long lastRefreshTime; // @synthesize lastRefreshTime=_lastRefreshTime;
@property(nonatomic) long long lastTid; // @synthesize lastTid=_lastTid;
@property(retain, nonatomic) NSMutableArray *mForumsArray; // @synthesize mForumsArray=_mForumsArray;
@property(nonatomic) _Bool needRefresh; // @synthesize needRefresh=_needRefresh;
- (void)preparForLoadADData:(long long)arg1;
- (void)prepareForAdData;
- (void)refreshRecommendBBS;
- (void)request;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)requestFirstPageWithPull;
- (void)requsetNextPage;
- (void)requsetNextPageFinished;
- (void)scrollToTop;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)setFullSrceenADViewData:(id)arg1;
- (void)setRefreshHead:(_Bool)arg1;
@property(nonatomic) long long stamp; // @synthesize stamp=_stamp;
@property(retain, nonatomic) NSString *unfollowTid; // @synthesize unfollowTid=_unfollowTid;
- (_Bool)shouldReloadInTimeInterval;
- (void)showADWithADData:(id)arg1;
- (void)showAdsHead;
- (void)showAttendName:(id)arg1;
- (void)showAttendTip:(id)arg1;
- (void)switchTitleAppear;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableViewHeaderRefresh;
- (void)transferToDay:(id)arg1;
- (void)transferToNight:(id)arg1;
- (void)updateForumsFollow:(id)arg1 tid:(id)arg2;
- (void)updateRecommendList:(id)arg1;
- (void)updatemForumsArray;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

